version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Senha10adaps
      MYSQL_USER: docker
      MYSQL_PASSWORD: Senha10adaps
      MYSQL_DATABASE: rest_with_spring_boot_and_java
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - farias-network
  rest-with-spring-boot-and-java-v2:
    image: marcelofarias2022/rest-with-spring-boot-and-java-v2
    restart: always
    build: ./rest-com-springboot-e-java
    working_dir: /rest-com-springboot-e-java
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_and_java?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Senha10adaps
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - farias-network
networks:
  farias-network:
    driver: bridge
